### ISSUE TITLE
Una vez has detectado una en su sitio, no puedes tenerla en cuenta en las blancas. Anúlalas

### ISSUE THREAD

**Issue by lmagarin** [Javierfs94/Reentrega-Mastermind-JS#1]
https://github.com/Javierfs94/Reentrega-Mastermind-JS/blob/1387076b36a92611ec8d718f79753370bd7a160b/js/masterMind.js#L56
Javi, realiza todas las pruebas que puedas para entenderlo.
¿Entiendes los errores que he puesto en el foro?

**Comment by Javierfs94** [comment]
La parte de pistas está solucionada por fin :)
