### ISSUE TITLE
Aquí cuentas más de una blanca, no? Si ya la has contado no puedes tenerla en cuenta de nuevo

### ISSUE THREAD

**Issue by lmagarin** [Javierfs94/Reentrega-Mastermind-JS#2]
https://github.com/Javierfs94/Reentrega-Mastermind-JS/blob/1387076b36a92611ec8d718f79753370bd7a160b/js/masterMind.js#L65

**Comment by Javierfs94** [comment]
Pistas solucionado en otro issue :)
